Parameters:
  ProjectName:
    Description: Nombre del proyecto
    Type: String

  JarName:
    Description: Nombre del jar
    Type: String

Resources:
    LambdaIMCRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub ${ProjectName}-LambdaExecutionRole
            AssumeRolePolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Principal:
                    Service:
                      - "ec2.amazonaws.com"
                  Action:
                    - "sts:AssumeRole"
            Path: /
            Policies:
              - PolicyName: !Sub ${ProjectName}-Role-Policy
                PolicyDocument:
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents",
                            "s3:*"
                          ],
                          "Resource": "arn:aws:logs:*:*:*"
                        }
                      ]
                    }

    LambdaIMC:
      Type: AWS::Lambda::Function
      Properties:
        Handler: "com.lambda.gradle.Test::handleRequest"
        Role: !GetAtt LambdaIMCRole.Arn
        Code:
          S3Bucket: "juanes-lambda-function"
          S3Key: !Ref JarName
        Runtime: "java8"
        Timeout: "25"
